CREATE TABLE CurrentOrder (
    order_id TEXT PRIMARY KEY NOT NULL,
    qr_token TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);